---
- name: "Install Uwsgi"
  apt: name={{item}} state=present
  with_items:
    - uwsgi
    - uwsgi-plugin-python3

- name: "Setup Uwsgi configuration files"
  template:
    src: "ACMGeneral_uwsgi.ini.j2"
    dest: "/etc/uwsgi/apps-available/ACMGeneral_uwsgi.ini"

- name: "Adding UWSGI symlink"
  file:
    src="/etc/uwsgi/apps-available/ACMGeneral_uwsgi.ini"
    dest="/etc/uwsgi/apps-enabled/ACMGeneral_uwsgi.ini"
    state=link
  notify:
    - restart uwsgi
