---
- name: "Install PostgreSQL"
  apt: name={{ item }} state=present
  with_items:
    - postgresql
    - postgresql-contrib
    - libpq-dev
  notify:
    - restart postgresql

- name: "Prepare Database"
  become: true
  become_user: postgres
  postgresql_db: 
    name={{db_name}}

- name: "Create user for database" 
  become: true
  become_user: postgres
  postgresql_user: 
    db={{db_name}} name={{db_user}} password={{db_password}} priv=ALL
